[[CovidSim]]
arch = "i686"
git-tree-sha1 = "a1bd50bbf56ad1d404f62573f0b3954ea5401400"
libc = "musl"
os = "linux"

    [[CovidSim.download]]
    sha256 = "026424767c29d6a387e6c5776b9dc7e31d102ca0c47e22fd6a455da97906bac3"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.i686-linux-musl.tar.gz"
[[CovidSim]]
arch = "aarch64"
git-tree-sha1 = "39248bdc24d38c2d197ec111a622cace1666a512"
libc = "musl"
os = "linux"

    [[CovidSim.download]]
    sha256 = "3e509f28df85f6c8b658f0d7c20c8e5e9afdbf0b113719cfa97449d5a30e6b1f"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.aarch64-linux-musl.tar.gz"
[[CovidSim]]
arch = "i686"
git-tree-sha1 = "ce33b299ce25c3ad5625be22f02a1c2d53c1a5f7"
os = "windows"

    [[CovidSim.download]]
    sha256 = "ce1b8a68062b3e84426f78cf252b2414b91406b63c4ae9132751393f988a13e6"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.i686-w64-mingw32.tar.gz"
[[CovidSim]]
arch = "x86_64"
git-tree-sha1 = "7073a1b99173425c42f1636c397658d54316e9d8"
os = "windows"

    [[CovidSim.download]]
    sha256 = "0e2b4876ec0dabab5f52f00c907f30a0a14acb83c2ac6876ca163b10a6d4c038"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.x86_64-w64-mingw32.tar.gz"
[[CovidSim]]
arch = "armv7l"
git-tree-sha1 = "f165a9a1b396fd866688f27f2b269ffe1e3fdd44"
libc = "glibc"
os = "linux"

    [[CovidSim.download]]
    sha256 = "6f5b3b42041d1e667e292567ba3f3b8c884f8039bf4aff6d229753f86e9bffa7"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.armv7l-linux-gnueabihf.tar.gz"
[[CovidSim]]
arch = "armv7l"
git-tree-sha1 = "e937e481a53c87a150136440ebc98b9ce9b0a6ce"
libc = "musl"
os = "linux"

    [[CovidSim.download]]
    sha256 = "3fdc9a12a6bd63b27d588830c1d378bd483b825454b90618b338aa70eaa83f99"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.armv7l-linux-musleabihf.tar.gz"
[[CovidSim]]
arch = "i686"
git-tree-sha1 = "c4b0595f265bac6a2b5d1ab3c513c2e978c5bfad"
libc = "glibc"
os = "linux"

    [[CovidSim.download]]
    sha256 = "f386061584d577ee657ad905410b9f5439076aab42b0373872049d011271df7d"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.i686-linux-gnu.tar.gz"
[[CovidSim]]
arch = "x86_64"
git-tree-sha1 = "f7fd665bd43a9ee9f2603bab74f33ff9c445b728"
libc = "glibc"
os = "linux"

    [[CovidSim.download]]
    sha256 = "4737804865bbbcc294cc7eba5cf8167139d3219446f27b6687a8003292a855f9"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.x86_64-linux-gnu.tar.gz"
[[CovidSim]]
arch = "powerpc64le"
git-tree-sha1 = "f1c92607d0019774a18535069772e8ce8645f4c1"
libc = "glibc"
os = "linux"

    [[CovidSim.download]]
    sha256 = "b9a1e4d8b24204776ff0ff0752853d0e22145d6d55e3e34c541d4aafd6084616"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.powerpc64le-linux-gnu.tar.gz"
[[CovidSim]]
arch = "x86_64"
git-tree-sha1 = "ac3a891ce599961850d67b280616146802e29312"
os = "macos"

    [[CovidSim.download]]
    sha256 = "f9d07cb547abd6c35f457cc77c5555b352122ed527ec4f94823a93f065b6e139"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.x86_64-apple-darwin14.tar.gz"
[[CovidSim]]
arch = "aarch64"
git-tree-sha1 = "0b0cb6b31c4b7905420939c738067bfdc325b46e"
libc = "glibc"
os = "linux"

    [[CovidSim.download]]
    sha256 = "7ef6f41e243a06d0b0aac84765383cca98cf7c5c4b954f0ec8c2efc2f4e12b60"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.aarch64-linux-gnu.tar.gz"
[[CovidSim]]
arch = "x86_64"
git-tree-sha1 = "461d9c6dac39b57e02cee723465293faa41c8703"
os = "freebsd"

    [[CovidSim.download]]
    sha256 = "234847d2bcef0ebd128221c098255e7e8a184ac641b560a193cc1a904288f780"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CovidSim]]
arch = "x86_64"
git-tree-sha1 = "3692909c19ea80bee312bd8d023731d1a23a2b31"
libc = "musl"
os = "linux"

    [[CovidSim.download]]
    sha256 = "ddf52baf4de4a27dc3fcc8f38e18b846e8047ee33094b6f7aa6173e4e3e2b5a4"
    url = "https://github.com/JuliaBinaryWrappers/CovidSim_jll.jl/releases/download/CovidSim-v0.8.0+1/CovidSim.v0.8.0.x86_64-linux-musl.tar.gz"
